FROM fedora:44

RUN dnf install -y \
        ffmpeg-free \
        libva-utils \
        python3 \
        python3-pip \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-44.noarch.rpm \
    && dnf install -y --allowerasing \
        mesa-va-drivers-freeworld \
        intel-media-driver \
        libva-intel-driver \
    && dnf clean all \
    && rm -rf /var/cache/dnf

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 3000

ENV DEV=1

CMD ["python3", "backend/main.py"]
